# Generated by Django 5.1.5 on 2025-01-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='box_type',
        ),
    ]
