# Generated by Django 5.1.5 on 2025-01-21 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_remove_box_box_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='box_type',
            field=models.CharField(choices=[('маленький до 3м', 'Маленький до 3м'), ('стандартный от 3м до 10м', 'Стандартный от 3м до 10м'), ('большой от 10м', 'Большой от 10м')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
