# Generated by Django 5.1.5 on 2025-01-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_box_box_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='box_area',
        ),
    ]
