# Generated by Django 5.1.5 on 2025-01-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField()),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("link_number", models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
